Write-Host "=== 当前项目状态 ==="
Write-Host ""
Write-Host "GitHub Actions 配置:"
Test-Path ".github/workflows/build-ios.yml"
Write-Host ""
Write-Host "iOS 项目:"
Test-Path "ios/"
Write-Host ""
Write-Host "前端构建产物:"
Test-Path "dist/"
Write-Host ""
Write-Host "Android 项目:"
Test-Path "android/"